[package]
name = "ecdsa_k_hotp_account_contract2"
type = "contract"
authors = [ "" ]
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.55.1", directory = "noir-projects/aztec-nr/aztec" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.55.1", directory = "noir-projects/aztec-nr/authwit" }
ecdsa_public_key_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.55.1", directory = "noir-projects/noir-contracts/contracts/ecdsa_public_key_note" }
token_portal_content_hash_lib = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.55.1", directory = "noir-projects/noir-contracts/contracts/token_portal_content_hash_lib" }
token = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.55.1", directory = "noir-projects/noir-contracts/contracts/token_contract" }
types = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.55.1", directory = "noir-projects/noir-protocol-circuits/crates/types" }
