[package]
name = "ecdsa_k_account_contract"
authors = [""]
compiler_version = ">=0.33.0"
type = "contract"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="barretenberg-v0.49.2", directory="noir-projects/aztec-nr/aztec" }
authwit = { git="https://github.com/AztecProtocol/aztec-packages/", tag="barretenberg-v0.49.2", directory="noir-projects/aztec-nr/authwit" }
ecdsa_public_key_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="barretenberg-v0.49.2", directory="noir-projects/noir-contracts/contracts/ecdsa_public_key_note" }