[package]
name = "schnorr_hardcoded_account_contract"
type = "contract"
authors = [""]
compiler_version = ">=0.33.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="barretenberg-v0.49.2", directory="noir-projects/aztec-nr/aztec" }
authwit = { git="https://github.com/AztecProtocol/aztec-packages/", tag="barretenberg-v0.49.2", directory="noir-projects/aztec-nr/authwit" }